// Code generated by provider-slack generation tools. DO NOT EDIT.

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ConversationInitParameters struct {

	// Archive the Slack channel on deletion (archive, the upstream default), or leave it unchanged (none).
	// Either of none or archive
	ActionOnDestroy *string `json:"actionOnDestroy,omitempty" tf:"action_on_destroy,omitempty"`

	// Permit upstream removal of unlisted members (kick, the upstream default), or retain them (none).
	// Either of none or kick
	ActionOnUpdatePermanentMembers *string `json:"actionOnUpdatePermanentMembers,omitempty" tf:"action_on_update_permanent_members,omitempty"`

	// Adopt an existing channel when creation reports name_taken; unarchive before applying settings. Set true to restore a deleted declaration with the same Slack ID.
	AdoptExistingChannel *bool `json:"adoptExistingChannel,omitempty" tf:"adopt_existing_channel,omitempty"`

	// Desired archive state. Set false to restore an adopted channel.
	IsArchived *bool `json:"isArchived,omitempty" tf:"is_archived,omitempty"`

	// Desired privacy. Upstream privacy changes use the Slack Admin API and require Enterprise Grid permissions.
	IsPrivate *bool `json:"isPrivate,omitempty" tf:"is_private,omitempty"`

	// generated channel ID, not this name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Declared Slack user IDs. Missing declared members are restored; upstream updates may remove unlisted members except the OAuth principal and channel creator.
	// +listType=set
	PermanentMembers []*string `json:"permanentMembers,omitempty" tf:"permanent_members,omitempty"`

	Purpose *string `json:"purpose,omitempty" tf:"purpose,omitempty"`

	// place workspace move.
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	Topic *string `json:"topic,omitempty" tf:"topic,omitempty"`
}

type ConversationObservation struct {

	// Archive the Slack channel on deletion (archive, the upstream default), or leave it unchanged (none).
	// Either of none or archive
	ActionOnDestroy *string `json:"actionOnDestroy,omitempty" tf:"action_on_destroy,omitempty"`

	// Permit upstream removal of unlisted members (kick, the upstream default), or retain them (none).
	// Either of none or kick
	ActionOnUpdatePermanentMembers *string `json:"actionOnUpdatePermanentMembers,omitempty" tf:"action_on_update_permanent_members,omitempty"`

	// Adopt an existing channel when creation reports name_taken; unarchive before applying settings. Set true to restore a deleted declaration with the same Slack ID.
	AdoptExistingChannel *bool `json:"adoptExistingChannel,omitempty" tf:"adopt_existing_channel,omitempty"`

	Created *int64 `json:"created,omitempty" tf:"created,omitempty"`

	Creator *string `json:"creator,omitempty" tf:"creator,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Desired archive state. Set false to restore an adopted channel.
	IsArchived *bool `json:"isArchived,omitempty" tf:"is_archived,omitempty"`

	IsExtShared *bool `json:"isExtShared,omitempty" tf:"is_ext_shared,omitempty"`

	IsGeneral *bool `json:"isGeneral,omitempty" tf:"is_general,omitempty"`

	IsOrgShared *bool `json:"isOrgShared,omitempty" tf:"is_org_shared,omitempty"`

	// Desired privacy. Upstream privacy changes use the Slack Admin API and require Enterprise Grid permissions.
	IsPrivate *bool `json:"isPrivate,omitempty" tf:"is_private,omitempty"`

	IsShared *bool `json:"isShared,omitempty" tf:"is_shared,omitempty"`

	// generated channel ID, not this name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Declared Slack user IDs. Missing declared members are restored; upstream updates may remove unlisted members except the OAuth principal and channel creator.
	// +listType=set
	PermanentMembers []*string `json:"permanentMembers,omitempty" tf:"permanent_members,omitempty"`

	Purpose *string `json:"purpose,omitempty" tf:"purpose,omitempty"`

	// place workspace move.
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	Topic *string `json:"topic,omitempty" tf:"topic,omitempty"`
}

type ConversationParameters struct {

	// Archive the Slack channel on deletion (archive, the upstream default), or leave it unchanged (none).
	// Either of none or archive
	// +kubebuilder:validation:Optional
	ActionOnDestroy *string `json:"actionOnDestroy,omitempty" tf:"action_on_destroy,omitempty"`

	// Permit upstream removal of unlisted members (kick, the upstream default), or retain them (none).
	// Either of none or kick
	// +kubebuilder:validation:Optional
	ActionOnUpdatePermanentMembers *string `json:"actionOnUpdatePermanentMembers,omitempty" tf:"action_on_update_permanent_members,omitempty"`

	// Adopt an existing channel when creation reports name_taken; unarchive before applying settings. Set true to restore a deleted declaration with the same Slack ID.
	// +kubebuilder:validation:Optional
	AdoptExistingChannel *bool `json:"adoptExistingChannel,omitempty" tf:"adopt_existing_channel,omitempty"`

	// Desired archive state. Set false to restore an adopted channel.
	// +kubebuilder:validation:Optional
	IsArchived *bool `json:"isArchived,omitempty" tf:"is_archived,omitempty"`

	// Desired privacy. Upstream privacy changes use the Slack Admin API and require Enterprise Grid permissions.
	// +kubebuilder:validation:Optional
	IsPrivate *bool `json:"isPrivate,omitempty" tf:"is_private,omitempty"`

	// generated channel ID, not this name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Declared Slack user IDs. Missing declared members are restored; upstream updates may remove unlisted members except the OAuth principal and channel creator.
	// +kubebuilder:validation:Optional
	// +listType=set
	PermanentMembers []*string `json:"permanentMembers,omitempty" tf:"permanent_members,omitempty"`

	// +kubebuilder:validation:Optional
	Purpose *string `json:"purpose,omitempty" tf:"purpose,omitempty"`

	// place workspace move.
	// +kubebuilder:validation:Optional
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// +kubebuilder:validation:Optional
	Topic *string `json:"topic,omitempty" tf:"topic,omitempty"`
}

// ConversationSpec defines the desired state of Conversation
type ConversationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ConversationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConversationInitParameters `json:"initProvider,omitempty"`
}

// ConversationStatus defines the observed state of Conversation.
type ConversationStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ConversationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Conversation is the Schema for the Conversations API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,slack}
type Conversation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ConversationSpec   `json:"spec"`
	Status ConversationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConversationList contains a list of Conversations
type ConversationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Conversation `json:"items"`
}

// Repository type metadata.
var (
	Conversation_Kind             = "Conversation"
	Conversation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Conversation_Kind}.String()
	Conversation_KindAPIVersion   = Conversation_Kind + "." + CRDGroupVersion.String()
	Conversation_GroupVersionKind = CRDGroupVersion.WithKind(Conversation_Kind)
)

func init() {
	SchemeBuilder.Register(&Conversation{}, &ConversationList{})
}
