//go:build !ignore_autogenerated

// Code generated by provider-slack generation tools. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Conversation) DeepCopyInto(out *Conversation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Conversation.
func (in *Conversation) DeepCopy() *Conversation {
	if in == nil {
		return nil
	}
	out := new(Conversation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Conversation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationInitParameters) DeepCopyInto(out *ConversationInitParameters) {
	*out = *in
	if in.ActionOnDestroy != nil {
		in, out := &in.ActionOnDestroy, &out.ActionOnDestroy
		*out = new(string)
		**out = **in
	}
	if in.ActionOnUpdatePermanentMembers != nil {
		in, out := &in.ActionOnUpdatePermanentMembers, &out.ActionOnUpdatePermanentMembers
		*out = new(string)
		**out = **in
	}
	if in.AdoptExistingChannel != nil {
		in, out := &in.AdoptExistingChannel, &out.AdoptExistingChannel
		*out = new(bool)
		**out = **in
	}
	if in.IsArchived != nil {
		in, out := &in.IsArchived, &out.IsArchived
		*out = new(bool)
		**out = **in
	}
	if in.IsPrivate != nil {
		in, out := &in.IsPrivate, &out.IsPrivate
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PermanentMembers != nil {
		in, out := &in.PermanentMembers, &out.PermanentMembers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Purpose != nil {
		in, out := &in.Purpose, &out.Purpose
		*out = new(string)
		**out = **in
	}
	if in.TeamID != nil {
		in, out := &in.TeamID, &out.TeamID
		*out = new(string)
		**out = **in
	}
	if in.Topic != nil {
		in, out := &in.Topic, &out.Topic
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationInitParameters.
func (in *ConversationInitParameters) DeepCopy() *ConversationInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConversationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationList) DeepCopyInto(out *ConversationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Conversation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationList.
func (in *ConversationList) DeepCopy() *ConversationList {
	if in == nil {
		return nil
	}
	out := new(ConversationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConversationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationObservation) DeepCopyInto(out *ConversationObservation) {
	*out = *in
	if in.ActionOnDestroy != nil {
		in, out := &in.ActionOnDestroy, &out.ActionOnDestroy
		*out = new(string)
		**out = **in
	}
	if in.ActionOnUpdatePermanentMembers != nil {
		in, out := &in.ActionOnUpdatePermanentMembers, &out.ActionOnUpdatePermanentMembers
		*out = new(string)
		**out = **in
	}
	if in.AdoptExistingChannel != nil {
		in, out := &in.AdoptExistingChannel, &out.AdoptExistingChannel
		*out = new(bool)
		**out = **in
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = new(int64)
		**out = **in
	}
	if in.Creator != nil {
		in, out := &in.Creator, &out.Creator
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsArchived != nil {
		in, out := &in.IsArchived, &out.IsArchived
		*out = new(bool)
		**out = **in
	}
	if in.IsExtShared != nil {
		in, out := &in.IsExtShared, &out.IsExtShared
		*out = new(bool)
		**out = **in
	}
	if in.IsGeneral != nil {
		in, out := &in.IsGeneral, &out.IsGeneral
		*out = new(bool)
		**out = **in
	}
	if in.IsOrgShared != nil {
		in, out := &in.IsOrgShared, &out.IsOrgShared
		*out = new(bool)
		**out = **in
	}
	if in.IsPrivate != nil {
		in, out := &in.IsPrivate, &out.IsPrivate
		*out = new(bool)
		**out = **in
	}
	if in.IsShared != nil {
		in, out := &in.IsShared, &out.IsShared
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PermanentMembers != nil {
		in, out := &in.PermanentMembers, &out.PermanentMembers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Purpose != nil {
		in, out := &in.Purpose, &out.Purpose
		*out = new(string)
		**out = **in
	}
	if in.TeamID != nil {
		in, out := &in.TeamID, &out.TeamID
		*out = new(string)
		**out = **in
	}
	if in.Topic != nil {
		in, out := &in.Topic, &out.Topic
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationObservation.
func (in *ConversationObservation) DeepCopy() *ConversationObservation {
	if in == nil {
		return nil
	}
	out := new(ConversationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationParameters) DeepCopyInto(out *ConversationParameters) {
	*out = *in
	if in.ActionOnDestroy != nil {
		in, out := &in.ActionOnDestroy, &out.ActionOnDestroy
		*out = new(string)
		**out = **in
	}
	if in.ActionOnUpdatePermanentMembers != nil {
		in, out := &in.ActionOnUpdatePermanentMembers, &out.ActionOnUpdatePermanentMembers
		*out = new(string)
		**out = **in
	}
	if in.AdoptExistingChannel != nil {
		in, out := &in.AdoptExistingChannel, &out.AdoptExistingChannel
		*out = new(bool)
		**out = **in
	}
	if in.IsArchived != nil {
		in, out := &in.IsArchived, &out.IsArchived
		*out = new(bool)
		**out = **in
	}
	if in.IsPrivate != nil {
		in, out := &in.IsPrivate, &out.IsPrivate
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PermanentMembers != nil {
		in, out := &in.PermanentMembers, &out.PermanentMembers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Purpose != nil {
		in, out := &in.Purpose, &out.Purpose
		*out = new(string)
		**out = **in
	}
	if in.TeamID != nil {
		in, out := &in.TeamID, &out.TeamID
		*out = new(string)
		**out = **in
	}
	if in.Topic != nil {
		in, out := &in.Topic, &out.Topic
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationParameters.
func (in *ConversationParameters) DeepCopy() *ConversationParameters {
	if in == nil {
		return nil
	}
	out := new(ConversationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationSpec) DeepCopyInto(out *ConversationSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationSpec.
func (in *ConversationSpec) DeepCopy() *ConversationSpec {
	if in == nil {
		return nil
	}
	out := new(ConversationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationStatus) DeepCopyInto(out *ConversationStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationStatus.
func (in *ConversationStatus) DeepCopy() *ConversationStatus {
	if in == nil {
		return nil
	}
	out := new(ConversationStatus)
	in.DeepCopyInto(out)
	return out
}
