// Code generated by provider-slack generation tools. DO NOT EDIT.

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Conversation) Hub() {}
